---
title: "pseudo Facebook Analysis"
author: "Stacey Lee"
date: "March 30, 2016"
output:
  html_document:
    fig_caption: yes
    keep_md: yes
---
### Load libraries and file
```{r}
library(ggplot2)
pf <- read.csv('pseudo_facebook (1).tsv', sep = '\t')
```

### Plot histogram of birthdays
```{r}
ggplot(data = pf, aes(x = dob_day)) + 
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = 1:31) + 
  facet_wrap(~dob_month) + xlab('Birthdate') + 
  ylab('Number of users with birthdate')
```

### Plot histogram of friend count
```{r}
ggplot(data = pf, aes(x = friend_count)) + geom_histogram() +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) + 
  xlab('Friend count') + 
  ylab('Number of users with x friends')

ggplot(data = pf, aes(x = friend_count)) + geom_histogram() + 
  scale_x_log10() + xlab('Log of friend count') + 
  ylab('Number of users with x friends')

ggplot(data = pf, aes(x = friend_count)) + geom_histogram() + 
  scale_x_sqrt() + xlab('Square root of friend count') + 
  ylab('Number of users with x friends')
```

### Plot histogram of friend count by gender
```{r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)

ggplot(aes(x = friend_count, y = ..count../sum(..count..)), data = subset(pf, !is.na(gender))) +
  geom_freqpoly(aes(color = gender), binwidth=10) + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
  xlab('Friend count') + 
  ylab('Percentage of users with x friends')
```

### Plot histogram of tenure on facebook
```{r}
ggplot(aes(x = tenure / 365), data = pf) + 
  geom_histogram(color = 'black', fill = '#F79420') + 
  scale_x_continuous(breaks = seq(1, 7, 1), limits = c(0, 7)) + 
  xlab('Number of years using Facebook') + 
  ylab('Number of users in sample')
```

### Plot histogram of age
```{r}
ggplot(aes(x = age), data = pf) + 
  geom_histogram(binwidth = 1, fill = '#5761AB') + 
  scale_x_continuous(breaks = seq(13, 113, 5)) + 
  xlab('Age') + 
  ylab('Number of users in sample')
```

### Plot histogram of likes generated by gender
```{r}
ggplot(aes(x = www_likes), data = subset(pf, !is.na(gender))) + 
  geom_freqpoly(aes(color = gender)) + 
  scale_x_log10() + xlab('Number of likes generated') + ylab('Number of users in sample')

by(pf$www_likes, pf$gender, sum)
```

### Plot boxplot of friend count by gender
```{r}
by(pf$friend_count, pf$gender, summary)

qplot(x = gender, y = friend_count, data = subset(pf, !is.na(gender)),
      geom = 'boxplot') + coord_cartesian(ylim = c(0, 250))
```

### Plot boxplot of friendships initiated by gender
```{r}
by(pf$friendships_initiated, pf$gender, summary)

qplot(x = gender, y = friendships_initiated, data = subset(pf, !is.na(gender)),
      geom = 'boxplot') + coord_cartesian(ylim = c(0, 150))
```

# Mobile check in analysis
```{r}
summary(pf$mobile_likes)

summary(pf$mobile_likes > 0)

mobile_check_in <- NA
pf$mobile_check_in <- ifelse(pf$mobile_likes > 0, 1, 0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
sum(pf$mobile_check_in == 1)/length(pf$mobile_check_in)

```

